from .DeleteSubmissionsView import DeleteSubmissionsView
from .EditSubmissionsView import EditSubmissionsView
from .SubmissionsDetailView import SubmissionsDetailView
from .SubmissionsView import SubmissionsView
from .SubmitWorkView import SubmitWorkView
from .WorkSubmissionsView import WorkSubmissionsView
