from .DeleteSubmissionsView import DeleteSubmissionsView
from .EditSubmissionsView import EditSubmissionsView
from .MySubmittedWorkView import MySubmittedWorkView
from .SubmissionsDetailView import SubmissionsDetailView
from .SubmissionsView import SubmissionsView
from .SubmitWorkView import SubmitWorkView
from .UserSubmittedWorkView import UserSubmittedWorkView
from .WorkSubmissionsView import WorkSubmissionsView
