from .AssignedWorkView import AssignedWorkView
from .AssignWorkView import AssignWorkView
from .CreateWorkView import CreateWorkView
from .DeleteWorkView import DeleteWorkView
from .DownloadImagesZipView import DownloadImagesZipView
from .DownloadWorkFileView import DownloadWorkFileView
from .DownloadWorkImageView import DownloadWorkImageView
from .EditWorkView import EditWorkView
from .MarkAsReadView import MarkAsReadView
from .QualityIssuesWorkView import QualityIssuesWorkView
from .RevokedWorkView import RevokedWorkView
from .RevokeWorkView import RevokeWorkView
from .UptakenWorkView import UptakenWorkView
from .UptakeWorkView import UptakeWorkView
from .UserAssignedWorkView import UserAssignedWorkView
from .UserQualityIssuesWorkView import UserQualityIssuesWorkView
from .UserRevokedWorkView import UserRevokedWorkView
from .UserUptakenWorkView import UserUptakenWorkView
from .WorkDetailView import WorkDetailView
from .WorkView import WorkView
from .TestingView import TestingView
from .WorkFileUploadView import WorkFileUploadView
from .WorkImageUploadView import WorkImageUploadView
from .DeleteWorkImageView import DeleteWorkImageView
