from .AssignedWorkView import AssignedWorkView
from .AssignWorkView import AssignWorkView
from .CreateWorkView import CreateWorkView
from .DeleteWorkView import DeleteWorkView
from .EditWorkView import EditWorkView
from .MarkAsReadView import MarkAsReadView
from .RevokeWorkView import RevokeWorkView
from .UptakenWorkView import UptakenWorkView
from .UptakeWorkView import UptakeWorkView
from .WorkDetailView import WorkDetailView
from .WorkView import WorkView
