# Generated by Django 5.0.2 on 2024-07-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submit_before', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In progress'), ('Not started', 'Not started')], max_length=100)),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'revisions',
            },
        ),
        migrations.CreateModel(
            name='RevisionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('file', models.FileField(upload_to='revision_message_files')),
                ('image', models.ImageField(upload_to='revision_message_images')),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'revision_messages',
            },
        ),
    ]
