# Generated by Django 5.0.2 on 2024-07-13 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submit_before', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In progress'), ('Not started', 'Not started')], max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revised_work', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='a_work.work')),
            ],
            options={
                'db_table': 'revisions',
            },
        ),
        migrations.CreateModel(
            name='RevisionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('file', models.FileField(upload_to='revision_message_files')),
                ('image', models.ImageField(upload_to='revision_message_images')),
                ('is_read', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='a_revisions.revision')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revision_messages',
            },
        ),
    ]
