# Generated by Django 5.0.2 on 2024-07-16 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_revisions', '0001_initial'),
        ('a_work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revised_work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revision',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='a_work.work'),
        ),
        migrations.AddField(
            model_name='revisionmessage',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='a_revisions.revision'),
        ),
        migrations.AddField(
            model_name='revisionmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
