# Generated by Django 5.0.2 on 2024-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_revisions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='is_open',
            new_name='opened_by_reviewer',
        ),
        migrations.AddField(
            model_name='revision',
            name='opened_by_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='revision',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In progress'), ('Not started', 'Not started')], default='Not started', max_length=100),
        ),
    ]
