# Generated by Django 5.0.2 on 2024-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_revisions', '0005_alter_revision_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='opened_by_reviewer',
            field=models.BooleanField(default=True),
        ),
    ]
