# Generated by Django 5.0.2 on 2025-02-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_revisions', '0007_alter_revisionmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ['-submit_before']},
        ),
    ]
