# Generated by Django 5.0.2 on 2025-02-23 12:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_revisions', '0008_alter_revision_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionmessage',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='academic-portal/revision-message-files/'),
        ),
        migrations.AlterField(
            model_name='revisionmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='academic-portal/revision-message-images/'),
        ),
    ]
