# Generated by Django 5.0.2 on 2024-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Nearing Deadline', 'Nearing Deadline'), ('New Revision', 'New Revision'), ('Update Profile', 'Update Profile'), ('System Notification', 'System Notification'), ('Revoked Work', 'Revoked Work'), ('Uptaken Work', 'Uptaken Work'), ('Assigned Work', 'Assigned Work'), ('New Revision', 'New Revision')], max_length=50),
        ),
    ]
