# Generated by Django 5.0.2 on 2024-07-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_notifications', '0005_alter_notificationuser_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
    ]
