# Generated by Django 5.0.2 on 2024-07-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_notifications', '0007_alter_notificationuser_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_association', to='a_notifications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_association', to=settings.AUTH_USER_MODEL),
        ),
    ]
