# Generated by Django 5.0.2 on 2024-07-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0003_rename_location_profile_country_profile_county_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmedialink',
            unique_together={('platform', 'profile')},
        ),
    ]
