# Generated by Django 5.0.2 on 2024-07-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0004_alter_socialmedialink_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
