# Generated by Django 5.0.2 on 2024-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0006_profile_country_profile_county_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(null=True),
        ),
    ]
