# Generated by Django 5.0.2 on 2025-02-23 12:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0008_alter_profile_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='academic-portal/profile-pics/'),
        ),
    ]
