# Generated by Django 5.0.2 on 2024-07-13 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='RevokedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revoked_works',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_code', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Essay', 'Essay'), ('Reflection', 'Reflection_Paper')], max_length=100)),
                ('words', models.IntegerField()),
                ('comment', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In progress'), ('Not started', 'Not started')], max_length=100)),
                ('is_submitted', models.BooleanField(default=False)),
                ('has_writer', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_work', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_work', to=settings.AUTH_USER_MODEL)),
                ('bookmarked_by', models.ManyToManyField(related_name='bookmarks', through='a_work.Bookmark', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ManyToManyField(related_name='revoked_work', through='a_work.RevokedWork', to=settings.AUTH_USER_MODEL)),
                ('uptaken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uptaken_work', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.AddField(
            model_name='revokedwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_work.work'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_work.work'),
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='work_files')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='a_work.work')),
            ],
            options={
                'db_table': 'work_files',
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='work_images')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='a_work.work')),
            ],
            options={
                'db_table': 'work_images',
            },
        ),
    ]
