# Generated by Django 5.0.2 on 2024-07-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='assigned_is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='uptaken_is_read',
            field=models.BooleanField(default=False),
        ),
    ]
