# Generated by Django 5.0.2 on 2024-07-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0002_work_assigned_is_read_work_uptaken_is_read'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='defaultwork',
            table='default_work',
        ),
    ]
