# Generated by Django 5.0.2 on 2024-07-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0003_alter_defaultwork_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultwork',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-created_at',)},
        ),
    ]
