# Generated by Django 5.0.2 on 2024-07-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0004_alter_defaultwork_options_alter_work_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='revoked_by',
        ),
        migrations.DeleteModel(
            name='RevokedWork',
        ),
    ]
