# Generated by Django 5.0.2 on 2025-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0006_type_alter_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(blank=True, choices=[('Essay', 'Essay'), ('Reflection Paper', 'Reflection_Paper')], default='Essay', max_length=100),
        ),
    ]
