# Generated by Django 5.0.2 on 2025-01-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0008_alter_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='a_work.type'),
        ),
    ]
