# Generated by Django 5.0.2 on 2025-02-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0009_alter_work_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
    ]
