# Generated by Django 5.0.2 on 2025-02-23 12:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_work', '0011_alter_workimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='academic-portal/work-files/'),
        ),
    ]
