# Generated by Django 5.0.2 on 2024-07-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created_at',)},
        ),
    ]
