# Generated by Django 5.0.2 on 2024-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_submissions', '0004_submission_claimed_by_submission_is_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files'),
        ),
    ]
