# Generated by Django 5.0.2 on 2024-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_submissions', '0005_alter_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
    ]
