# Generated by Django 5.0.2 on 2025-02-23 12:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_submissions', '0007_alter_submission_claimed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='academic-portal/submission-files/'),
        ),
    ]
