from .AnalyticsView import AnalyticsView
from .ChangePasswordView import ChangePasswordView
from .ContactInfoView import ContactInfoView
from .DeletePictureView import DeletePictureView
from .MyProfile import MyProfile
from .Profile import Profile
from .ProfileUpdateView import ProfileUpdateView
from .UpdatePictureView import UpdatePictureView
from .UserAnalyticsView import UserAnalyticsView
