# Generated by Django 5.0.2 on 2024-07-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
