# Generated by Django 5.0.2 on 2024-07-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0004_alter_registrationcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temporary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
