# Generated by Django 5.0.2 on 2024-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0006_alter_customuser_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
