# Generated by Django 5.0.2 on 2024-07-10 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0008_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 9, 29, 21, 601542, tzinfo=datetime.timezone.utc)),
        ),
    ]
