# Generated by Django 5.0.2 on 2024-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0012_registrationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcode',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
