# Generated by Django 5.0.2 on 2024-07-15 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0013_remove_registrationcode_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='is_changed_password',
            new_name='password_changed',
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL),
        ),
    ]
