# Generated by Django 5.0.2 on 2024-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0014_rename_is_changed_password_onboarding_password_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='duration_to_expire',
            field=models.DurationField(null=True),
        ),
    ]
