# Generated by Django 5.0.2 on 2024-07-15 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0015_registrationcode_duration_to_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='time_to_expire',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='duration_to_expire',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
    ]
