# Generated by Django 5.0.2 on 2024-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0016_registrationcode_time_to_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='time_to_expire',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
