# Generated by Django 5.0.2 on 2024-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0018_alter_registrationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
