# Generated by Django 5.0.2 on 2024-07-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauth', '0020_alter_emailotp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onboarding',
        ),
    ]
